# Generated by Django 5.0.4 on 2025-03-19 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_historicoestoque_preco_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoestoque',
            name='cnpj_cliente',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='registro_venda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de Estoque'), ('venda', 'Venda'), ('ajuste', 'Ajuste de Estoque'), ('alteracao_preco', 'Alteração de Preço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='valor_final_estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='valor_inicial_estoque',
            field=models.IntegerField(),
        ),
    ]
